import { log } from "console";
import { generateInternshipEmail } from "./groqservice.js";

export async function sendInternshipMail() {
const record = {
  "First Name": "Ramalingam",
  "Last Name": "Subramanian",
  "Title": "Founder",
  "Company Name": "AssetWorks AI",
  "Company Name (Email)": "AssetWorks AI",
  "Email": "ram.s@assetworks.in",
  "Email Status": "Verified",
  "Primary Email Source": "Apollo",
  "Primary Email Verification Source": "Apollo",
  "Email Confidence": null,
  "Primary Email Catch-All Status": "Not Catch-all",
  "Primary Email Last Verified At": "2025-07-21T03:06:22+00:00",
  "Departments": "C-Suite",
  "Contact Owner": "gdgrishikesh@gmail.com",
  "Work Direct Phone": "",
  "Home Phone": "",
  "Mobile Phone": "",
  "Corporate Phone": "",
  "Other Phone": "",
  "Stage": "Cold",
  "Lists": "",
  "Last Contacted": "",
  "Account Owner": "gdgrishikesh@gmail.com",
  "Employees": "3",
  "Industry": "financial services",
  "Keywords": "investment intelligence, ai powered research, fintech, investment anal…",
  "Person Linkedin URL": "http://www.linkedin.com/in/watsubram",
  "Website": "https://assetworks.ai",
  "Company Linkedin URL": "http://www.linkedin.com/company/assetworks-ai",
  "Facebook URL": "",
  "Twitter URL": "",
  "City": "Bengaluru",
  "State": "Karnataka",
  "Country": "India",
  "Company Address": "",
  "Company City": "",
  "Company State": "",
  "Company Country": "",
  "Company Phone": "",
  "Technologies": "Amazon CloudFront, Route 53, Gmail, Google Apps, Google Tag Manager, M…",
  "Annual Revenue": "",
  "Total Funding": "",
  "Latest Funding": "",
  "Latest Funding Amount": "",
  "Last Raised At": "",
  "Subsidiary Of": "",
  "Email Sent": "",
  "Email Open": "false",
  "Email Bounced": "false",
  "Replied": "false",
  "Demoed": "false",
  "Number of Retail Locations": "",
  "Apollo Contact ID": "687daeadd15693001d2462bf",
  "Apollo Account ID": "687daeadd15693001d2462c0",
  "Secondary Email": "",
  "Secondary Email Source": "",
  "Secondary Email Status": "",
  "Secondary Email Verification Source": "",
  "Tertiary Email": "",
  "Tertiary Email Source": "",
  "Tertiary Email Status": "",
  "Tertiary Email Verification Source": "",
  "Last Sent Date": "2025-07-29T19:25:09.171+00:00",
  "Created At": "2025-11-06T19:25:09.178+00:00",
  "Updated At": "2025-11-06T19:25:09.178+00:00",
  "__v": 0
};

const contactData = {
  firstName: record["First Name"],
  lastName: record["Last Name"],
  title: record["Title"],
  companyName: record["Company Name"],
  companyNameForEmails: record["Company Name (Email)"],
  email: record["Email"],
  emailStatus: record["Email Status"],
  primaryEmailSource: record["Primary Email Source"],
  primaryEmailVerificationSource: record["Primary Email Verification Source"],
  emailConfidence: record["Email Confidence"],
  primaryEmailCatchAllStatus: record["Primary Email Catch-All Status"],
  primaryEmailLastVerifiedAt: record["Primary Email Last Verified At"],
  departments: record["Departments"],
  contactOwner: record["Contact Owner"],
  workDirectPhone: record["Work Direct Phone"],
  homePhone: record["Home Phone"],
  mobilePhone: record["Mobile Phone"],
  corporatePhone: record["Corporate Phone"],
  otherPhone: record["Other Phone"],
  stage: record["Stage"],
  lists: record["Lists"],
  lastContacted: record["Last Contacted"],
  accountOwner: record["Account Owner"],
  employees: record["Employees"],
  industry: record["Industry"],
  keywords: record["Keywords"],
  personLinkedinUrl: record["Person Linkedin URL"],
  website: record["Website"],
  companyLinkedinUrl: record["Company Linkedin URL"],
  facebookUrl: record["Facebook URL"],
  twitterUrl: record["Twitter URL"],
  city: record["City"],
  state: record["State"],
  country: record["Country"],
  companyAddress: record["Company Address"],
  companyCity: record["Company City"],
  companyState: record["Company State"],
  companyCountry: record["Company Country"],
  companyPhone: record["Company Phone"],
  technologies: record["Technologies"],
  annualRevenue: record["Annual Revenue"],
  totalFunding: record["Total Funding"],
  latestFunding: record["Latest Funding"],
  latestFundingAmount: record["Latest Funding Amount"],
  lastRaisedAt: record["Last Raised At"],
  subsidiaryOf: record["Subsidiary Of"],
  emailSent: record["Email Sent"],
  emailOpen: record["Email Open"],
  emailBounced: record["Email Bounced"],
  replied: record["Replied"],
  demoed: record["Demoed"],
  numberOfRetailLocations: record["Number of Retail Locations"],
  apolloContactId: record["Apollo Contact ID"],
  apolloAccountId: record["Apollo Account ID"],
  secondaryEmail: record["Secondary Email"],
  secondaryEmailSource: record["Secondary Email Source"],
  secondaryEmailStatus: record["Secondary Email Status"],
  secondaryEmailVerificationSource: record["Secondary Email Verification Source"],
  tertiaryEmail: record["Tertiary Email"],
  tertiaryEmailSource: record["Tertiary Email Source"],
  tertiaryEmailStatus: record["Tertiary Email Status"],
  tertiaryEmailVerificationSource: record["Tertiary Email Verification Source"],
  lastSentDate: record["Last Sent Date"],
  createdAt: record["Created At"],
  updatedAt: record["Updated At"],
  __v: record["__v"]
};

console.log(contactData);


  console.log("entered in send email");
  ////
  
  ////
  

  const { subject, body } = await generateInternshipEmail(contactData);
  return {subject , body}
}


